name: sqflite_migrate
description: SQFLite migration tool
version: 0.3.0
repository: https://github.com/konstantinB1/sqflite-migrate

environment:
  sdk: ^3.3.1

dependencies:
  ansicolor: ^2.0.2
  sqflite_common_ffi: ^2.3.3
  path: ^1.8.0
  cli_util: ^0.4.1
  args: ^2.5.0
  ansi: ^0.4.2
  ansi_escapes: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.6

executables:
  sqflite_migrate: sqflite_migrate.dart
