name: sqflite_migrate
description: "Yet another migration solution to sqflite"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: "3.22.1"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  test: ^1.25.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/test_files/
